// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_vqsIoVb0_2UnCMiuudkJ1mrnl0B2x3A',
    appId: '1:560953273697:web:6687952f83501053f4e920',
    messagingSenderId: '560953273697',
    projectId: 'live-location-291ca',
    authDomain: 'live-location-291ca.firebaseapp.com',
    storageBucket: 'live-location-291ca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOBFsn1jfp0uuOHnCXHAqBwlxgmo9-USc',
    appId: '1:560953273697:android:da7373961be7b3b9f4e920',
    messagingSenderId: '560953273697',
    projectId: 'live-location-291ca',
    storageBucket: 'live-location-291ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEgmEN1qvWpW-BH4lYSnX3wZ4AhLOvS9w',
    appId: '1:560953273697:ios:02868ab3f81fe89bf4e920',
    messagingSenderId: '560953273697',
    projectId: 'live-location-291ca',
    storageBucket: 'live-location-291ca.firebasestorage.app',
    iosBundleId: 'com.example.liveTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEgmEN1qvWpW-BH4lYSnX3wZ4AhLOvS9w',
    appId: '1:560953273697:ios:02868ab3f81fe89bf4e920',
    messagingSenderId: '560953273697',
    projectId: 'live-location-291ca',
    storageBucket: 'live-location-291ca.firebasestorage.app',
    iosBundleId: 'com.example.liveTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_vqsIoVb0_2UnCMiuudkJ1mrnl0B2x3A',
    appId: '1:560953273697:web:371cf001b3cf5e19f4e920',
    messagingSenderId: '560953273697',
    projectId: 'live-location-291ca',
    authDomain: 'live-location-291ca.firebaseapp.com',
    storageBucket: 'live-location-291ca.firebasestorage.app',
  );
}
